-- ==========================================================================
-- SmartShop: Migração Auth - Supabase Auth nativo + RLS
-- Fase 2: Autenticação via auth.users com trigger de profile automático
-- ==========================================================================

-- 1. Remover colunas manuais de auth da tabela profiles
ALTER TABLE public.profiles DROP COLUMN IF EXISTS password;
ALTER TABLE public.profiles DROP COLUMN IF EXISTS email;

-- 2. Adicionar referência a auth.users (o id do profile passa a ser o id do auth.users)
-- Precisamos recriar a tabela profiles com a foreign key correta
DROP TABLE IF EXISTS public.pantry CASCADE;
DROP TABLE IF EXISTS public.items CASCADE;
DROP TABLE IF EXISTS public.lists CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- 3. Recriar profiles vinculada a auth.users
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    name TEXT NOT NULL DEFAULT 'Usuário SmartShop',
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Recriar tabelas com FK para o novo profiles
CREATE TABLE public.lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    is_shared BOOLEAN DEFAULT FALSE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_id BIGINT REFERENCES public.lists(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    quantity INTEGER DEFAULT 1,
    estimated_price NUMERIC(10, 2) DEFAULT 0.00,
    is_bought BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- O tipo enum já existe da migration anterior, não recriar
-- CREATE TYPE public.stock_level_enum ...

CREATE TABLE public.pantry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    stock_level public.stock_level_enum NOT NULL,
    quantity TEXT NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Índices
CREATE INDEX idx_lists_user_id ON public.lists(user_id);
CREATE INDEX idx_items_list_id ON public.items(list_id);
CREATE INDEX idx_pantry_user_id ON public.pantry(user_id);

-- 6. Trigger para criar profile automaticamente no signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, name, avatar_url)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'name', 'Usuário SmartShop'),
        NEW.raw_user_meta_data->>'avatar_url'
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 7. Habilitar Row Level Security (RLS) em todas as tabelas
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pantry ENABLE ROW LEVEL SECURITY;

-- 8. Policies: Profiles
CREATE POLICY "Users can view their own profile"
    ON public.profiles FOR SELECT
    USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile"
    ON public.profiles FOR UPDATE
    USING (auth.uid() = id);

-- 9. Policies: Lists
CREATE POLICY "Users can view their own lists"
    ON public.lists FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own lists"
    ON public.lists FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own lists"
    ON public.lists FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own lists"
    ON public.lists FOR DELETE
    USING (auth.uid() = user_id);

-- 10. Policies: Items (via list ownership)
CREATE POLICY "Users can view items from their lists"
    ON public.items FOR SELECT
    USING (list_id IN (SELECT id FROM public.lists WHERE user_id = auth.uid()));

CREATE POLICY "Users can create items in their lists"
    ON public.items FOR INSERT
    WITH CHECK (list_id IN (SELECT id FROM public.lists WHERE user_id = auth.uid()));

CREATE POLICY "Users can update items in their lists"
    ON public.items FOR UPDATE
    USING (list_id IN (SELECT id FROM public.lists WHERE user_id = auth.uid()));

CREATE POLICY "Users can delete items from their lists"
    ON public.items FOR DELETE
    USING (list_id IN (SELECT id FROM public.lists WHERE user_id = auth.uid()));

-- 11. Policies: Pantry
CREATE POLICY "Users can view their own pantry"
    ON public.pantry FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can create pantry items"
    ON public.pantry FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own pantry"
    ON public.pantry FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own pantry items"
    ON public.pantry FOR DELETE
    USING (auth.uid() = user_id);
