-- ==========================================================================
-- SmartShop: Migração Compartilhamento de Listas (Colaboração)
-- v0.4.0 - Tabela de colaboradores, RPC seguro de busca de e-mail e RLS
-- ==========================================================================

-- 1. Criar a tabela de colaboradores
CREATE TABLE IF NOT EXISTS public.list_collaborators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_id BIGINT REFERENCES public.lists(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE, -- NULL se o e-mail não estiver cadastrado ainda
    invited_email TEXT NOT NULL,
    role TEXT CHECK (role IN ('owner', 'editor', 'viewer')) DEFAULT 'editor',
    status TEXT CHECK (status IN ('pending', 'accepted')) DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE (list_id, invited_email)
);

-- 2. Índices de Performance
CREATE INDEX IF NOT EXISTS idx_list_collaborators_email ON public.list_collaborators(invited_email);
CREATE INDEX IF NOT EXISTS idx_list_collaborators_user_id ON public.list_collaborators(user_id);

-- 3. RPC Seguro para consultar usuários cadastrados sem expor a tabela auth.users publicamente
CREATE OR REPLACE FUNCTION public.get_user_by_email(email_to_search TEXT)
RETURNS TABLE (id UUID, name TEXT) 
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    RETURN QUERY
    SELECT u.id, COALESCE(p.name, 'Usuário SmartShop') AS name
    FROM auth.users u
    LEFT JOIN public.profiles p ON p.id = u.id
    WHERE LOWER(u.email) = LOWER(email_to_search);
END;
$$ LANGUAGE plpgsql;

-- 4. Atualizar o handle_new_user para associar automaticamente convites pendentes
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    -- Cria o perfil público
    INSERT INTO public.profiles (id, name, avatar_url)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'name', 'Usuário SmartShop'),
        NEW.raw_user_meta_data->>'avatar_url'
    );
    
    -- Vincula convites pendentes deste e-mail ao novo UUID criado
    UPDATE public.list_collaborators
    SET user_id = NEW.id
    WHERE LOWER(invited_email) = LOWER(NEW.email)
      AND user_id IS NULL;
      
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Habilitar RLS na tabela de colaboradores
ALTER TABLE public.list_collaborators ENABLE ROW LEVEL SECURITY;

-- 6. Políticas de RLS para list_collaborators

-- O dono da lista pode gerenciar (CRUD) colaboradores
CREATE POLICY "Dono da lista pode gerenciar colaboradores"
    ON public.list_collaborators FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.lists
            WHERE lists.id = list_collaborators.list_id
            AND lists.user_id = auth.uid()
        )
    );

-- Qualquer usuário logado pode ver convites enviados para ele
CREATE POLICY "Usuários podem visualizar seus convites"
    ON public.list_collaborators FOR SELECT
    USING (
        auth.uid() = user_id
    );

-- Colaboradores aceitos podem visualizar quem mais está na lista
CREATE POLICY "Colaboradores aceitos podem ver outros colaboradores"
    ON public.list_collaborators FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.list_collaborators lc
            WHERE lc.list_id = list_collaborators.list_id
            AND lc.user_id = auth.uid()
            AND lc.status = 'accepted'
        )
    );

-- O convidado pode atualizar o status do próprio convite (Aceitar/Recusar)
CREATE POLICY "Convidados podem responder ao convite"
    ON public.list_collaborators FOR UPDATE
    USING (
        auth.uid() = user_id
    );

-- O convidado pode excluir seu próprio convite (Recusar/Sair da lista)
CREATE POLICY "Convidados podem deletar seu próprio convite"
    ON public.list_collaborators FOR DELETE
    USING (
        auth.uid() = user_id
    );

-- 7. Ajustar Políticas de RLS da tabela LISTS para suportar compartilhamento

-- Atualizar política de SELECT para incluir colaboradores aceitos
DROP POLICY IF EXISTS "Users can view their own lists" ON public.lists;
CREATE POLICY "Usuários podem visualizar listas que possuem ou colaboram"
    ON public.lists FOR SELECT
    USING (
        auth.uid() = user_id
        OR
        EXISTS (
            SELECT 1 FROM public.list_collaborators
            WHERE list_collaborators.list_id = lists.id
            AND list_collaborators.user_id = auth.uid()
            AND list_collaborators.status = 'accepted'
        )
    );

-- 8. Ajustar Políticas de RLS da tabela ITEMS para suportar compartilhamento

-- Atualizar SELECT, INSERT, UPDATE, DELETE para itens baseando no acesso à lista pai
DROP POLICY IF EXISTS "Users can view items from their lists" ON public.items;
DROP POLICY IF EXISTS "Users can create items in their lists" ON public.items;
DROP POLICY IF EXISTS "Users can update items in their lists" ON public.items;
DROP POLICY IF EXISTS "Users can delete items from their lists" ON public.items;

CREATE POLICY "Usuários podem ver itens de suas listas ou compartilhadas"
    ON public.items FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.lists
            WHERE lists.id = items.list_id
            AND (
                lists.user_id = auth.uid()
                OR EXISTS (
                    SELECT 1 FROM public.list_collaborators
                    WHERE list_collaborators.list_id = lists.id
                    AND list_collaborators.user_id = auth.uid()
                    AND list_collaborators.status = 'accepted'
                )
            )
        )
    );

CREATE POLICY "Usuários podem adicionar itens em suas listas ou compartilhadas"
    ON public.items FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.lists
            WHERE lists.id = items.list_id
            AND (
                lists.user_id = auth.uid()
                OR EXISTS (
                    SELECT 1 FROM public.list_collaborators
                    WHERE list_collaborators.list_id = lists.id
                    AND list_collaborators.user_id = auth.uid()
                    AND list_collaborators.status = 'accepted'
                )
            )
        )
    );

CREATE POLICY "Usuários podem editar itens em suas listas ou compartilhadas"
    ON public.items FOR UPDATE
    USING (
        EXISTS (
            SELECT 1 FROM public.lists
            WHERE lists.id = items.list_id
            AND (
                lists.user_id = auth.uid()
                OR EXISTS (
                    SELECT 1 FROM public.list_collaborators
                    WHERE list_collaborators.list_id = lists.id
                    AND list_collaborators.user_id = auth.uid()
                    AND list_collaborators.status = 'accepted'
                )
            )
        )
    );

CREATE POLICY "Usuários podem excluir itens em suas listas ou compartilhadas"
    ON public.items FOR DELETE
    USING (
        EXISTS (
            SELECT 1 FROM public.lists
            WHERE lists.id = items.list_id
            AND (
                lists.user_id = auth.uid()
                OR EXISTS (
                    SELECT 1 FROM public.list_collaborators
                    WHERE list_collaborators.list_id = lists.id
                    AND list_collaborators.user_id = auth.uid()
                    AND list_collaborators.status = 'accepted'
                )
            )
        )
    );
