-- ==========================================================================
-- SmartShop: Migração Inicial - SQLite para PostgreSQL (Supabase)
-- Fase 1: Migração do banco de dados (autenticação Supabase Auth na Fase 2)
-- ==========================================================================

-- 1. Tabela de Perfis (substitui a antiga tabela 'users' do SQLite)
-- NOTA: Mantém email/password temporariamente para compatibilidade com o
-- sistema de login atual. Será migrado para auth.users na Fase 2.
CREATE TABLE public.profiles (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabela de Listas de Compras
CREATE TABLE public.lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    is_shared BOOLEAN DEFAULT FALSE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tabela de Itens da Lista
CREATE TABLE public.items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_id BIGINT REFERENCES public.lists(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    quantity INTEGER DEFAULT 1,
    estimated_price NUMERIC(10, 2) DEFAULT 0.00,
    is_bought BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Tipo Enumerado para nível de estoque
CREATE TYPE public.stock_level_enum AS ENUM ('Cheio', 'Baixo', 'Em Falta');

-- 5. Tabela da Despensa (Pantry)
CREATE TABLE public.pantry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    stock_level public.stock_level_enum NOT NULL,
    quantity TEXT NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Índices para performance
CREATE INDEX idx_lists_user_id ON public.lists(user_id);
CREATE INDEX idx_items_list_id ON public.items(list_id);
CREATE INDEX idx_pantry_user_id ON public.pantry(user_id);
